In [72]:
import urllib.request as req
import json
import pandas as pd
from sklearn import *

In [13]:
url = 'https://api.inews.qq.com/newsqa/v1/query/inner/publish/modules/list?modules=chinaDayList,chinaDayAddList,nowConfirmStatis,provinceCompare'
request = req.Request(url)
request.add_header("user-agent","Mozilla/5.0")
response = req.urlopen(request)
json_ret = json.loads(response.read())
data = json_ret['data']
chinaDayAddList = data['chinaDayAddList']
chinaDayList = data['chinaDayList']

In [52]:
df1 = pd.DataFrame(chinaDayAddList)
df2 = pd.DataFrame(chinaDayList)
df1 = df1[df1['date'] > '03.14']
df1 = df1[df1['date'] < '04.14']
df2 = df2[df2['date'] > '03.14']
df2 = df2[df2['date'] < '04.14']
df2

,healRate,localConfirm,local_acc_confirm,confirm,heal,nowConfirm,suspect,dead,deadRate,localConfirmH5,date,y,noInfect,noInfectH5,nowSevere,importedCase
16,35.8,11189,122456,410827,147084,253686,6,10057,2.4,11189,03.15,2022,9864,8169,11,16524
17,35.7,12426,123773,415480,148389,256755,14,10336,2.5,12426,03.16,2022,11029,9300,16,16615
18,35.7,14606,126234,420134,149838,259671,19,10625,2.5,14606,03.17,2022,12786,10984,18,16688
19,35.7,16530,128462,424297,151526,261879,7,10892,2.6,16530,03.18,2022,14318,12597,31,16759
20,35.8,18016,130199,427848,153047,263660,10,11141,2.6,18016,03.19,2022,16196,14501,35,16840
21,35.8,19617,132226,431271,154514,265370,14,11387,2.6,19617,03.20,2022,18327,16669,39,16920
22,35.8,21507,134564,434834,155494,267730,14,11610,2.7,21507,03.21,2022,20155,18521,42,16976
23,35.9,23659,137231,438647,157432,269360,12,11855,2.7,23659,03.22,2022,22000,20411,50,17052
24,36.2,24953,139285,441865,159794,270011,13,12060,2.7,24953,03.23,2022,24062,22564,50,17096
25,36.4,25710,140651,445069,161905,270903,16,12261,2.8,25710,03.24,2022,27046,25591,50,17161
26,36.7,26218,141986,447162,164215,270494,13,12453,2.8,26218,03.25,2022,30850,29443,50,17216
27,37.1,26571,143240,449283,166661,270030,13,12592,2.8,26571,03.26,2022,34508,33170,53,17253
28,37.3,26831,144515,451447,168586,270118,19,12743,2.8,26831,03.27,2022,38649,37291,58,17309
29,37.5,27021,145808,453469,170177,270382,15,12911,2.8,27021,03.28,2022,43425,42116,59,17370
30,37.9,27372,147437,455633,172755,269816,17,13062,2.9,27372,03.29,2022,49421,48154,62,17434
31,38.3,27843,149276,458299,175627,269475,18,13197,2.9,27843,03.30,2022,54911,53709,66,17470
32,38.7,29306,151103,460892,178163,269413,20,13316,2.9,29306,03.31,2022,57874,59056,66,17510
33,38.7,26467,153232,475180,183944,277800,19,13436,2.8,26467,04.01,2022,63886,62768,58,17553
34,38.8,25514,154738,483750,187850,282348,19,13552,2.8,25514,04.02,2022,73689,72584,57,17604
35,39.2,25105,156143,485913,190569,281681,17,13663,2.8,25105,04.03,2022,83364,82300,54,17643
36,39.5,24469,157378,487867,192850,281264,17,13753,2.8,24469,04.04,2022,96803,95777,63,17705
37,40.0,24024,158793,490130,196207,280083,16,13840,2.8,24024,04.05,2022,113950,112937,75,17737
38,40.4,23626,160116,492227,198627,279649,19,13951,2.8,23626,04.06,2022,132948,131955,85,17776
39,40.8,13353,161692,495323,201985,279290,23,14048,2.8,13353,04.07,2022,152693,151728,77,17812
40,41.3,22744,163042,497437,205491,277812,29,14134,2.8,22744,04.08,2022,174015,173083,79,17828
41,41.8,22589,164393,499486,208982,276307,28,14197,2.8,22589,04.09,2022,195948,195021,80,17861
42,42.1,22025,165577,501495,211238,275995,28,14262,2.8,22025,04.10,2022,219896,218997,76,17881
43,42.4,21991,140220,503565,213274,275972,26,14319,2.8,21991,04.11,2022,240624,239737,77,17902
44,42.8,21512,168362,505815,216382,275055,26,14378,2.8,21512,04.12,2022,258374,257493,87,17915
45,43.1,22514,171382,509824,219950,275434,15,14440,2.8,22514,04.13,2022,266230,265386,78,17936

In [53]:
acc_df = df2[['local_acc_confirm', 'nowConfirm', 'heal', 'dead', 'date']]
add_df = df1[['localConfirmadd', 'suspect', 'date']]

In [65]:
acc_df.columns = ['acc_confirm', 'confirm', 'acc_heal', 'acc_dead', 'date']
add_df.columns = ['confirm_add', 'suspect_add', 'date']
df = pd.merge(acc_df, add_df, 'left')
df

    acc_confirm  confirm  acc_heal  acc_dead   date  confirm_add  suspect_add
0        122456   253686    147084     10057  03.15       1860.0          1.0
1        123773   256755    148389     10336  03.16       1226.0          8.0
2        126234   259671    149838     10625  03.17       2388.0          6.0
3        128462   261879    151526     10892  03.18       2157.0          0.0
4        130199   263660    153047     11141  03.19       1656.0          3.0
5        132226   265370    154514     11387  03.20       1947.0          6.0
6        134564   267730    155494     11610  03.21       2281.0          0.0
7        137231   269360    157432     11855  03.22       2591.0          3.0
8        139285   270011    159794     12060  03.23       2010.0          1.0
9        140651   270903    161905     12261  03.24       1301.0          5.0
10       141986   270494    164215     12453  03.25       1280.0          1.0
11       143240   270030    166661     12592  03.26       1217.0          0.0
12       144515   270118    168586     12743  03.27       1219.0          6.0
13       145808   270382    170177     12911  03.28       1228.0          6.0
14       147437   269816    172755     13062  03.29       1565.0          2.0
15       149276   269475    175627     13197  03.30       1803.0          2.0
16       151103   269413    178163     13316  03.31       1787.0          2.0
17       153232   277800    183944     13436  04.01       2086.0          0.0
18       154738   282348    187850     13552  04.02       1455.0          0.0
19       156143   281681    190569     13663  04.03       1366.0          0.0
20       157378   281264    192850     13753  04.04       1173.0          0.0
21       158793   280083    196207     13840  04.05       1383.0          0.0
22       160116   279649    198627     13951  04.06       1284.0          4.0
23       161692   279290    201985     14048  04.07       1540.0          4.0
24       163042   277812    205491     14134  04.08          NaN          NaN
25       164393   276307    208982     14197  04.09       1318.0          0.0
26       165577   275995    211238     14262  04.10       1164.0          0.0
27       140220   275972    213274     14319  04.11       1251.0          0.0
28       168362   275055    216382     14378  04.12       1500.0          0.0
29       171382   275434    219950     14440  04.13       2999.0          0.0

In [66]:
df['suspect_add'].fillna(0)
df['confirm_add'].fillna(df['confirm_add'].mean())
df

    acc_confirm  confirm  acc_heal  acc_dead   date  confirm_add  suspect_add
0        122456   253686    147084     10057  03.15       1860.0          1.0
1        123773   256755    148389     10336  03.16       1226.0          8.0
2        126234   259671    149838     10625  03.17       2388.0          6.0
3        128462   261879    151526     10892  03.18       2157.0          0.0
4        130199   263660    153047     11141  03.19       1656.0          3.0
5        132226   265370    154514     11387  03.20       1947.0          6.0
6        134564   267730    155494     11610  03.21       2281.0          0.0
7        137231   269360    157432     11855  03.22       2591.0          3.0
8        139285   270011    159794     12060  03.23       2010.0          1.0
9        140651   270903    161905     12261  03.24       1301.0          5.0
10       141986   270494    164215     12453  03.25       1280.0          1.0
11       143240   270030    166661     12592  03.26       1217.0          0.0
12       144515   270118    168586     12743  03.27       1219.0          6.0
13       145808   270382    170177     12911  03.28       1228.0          6.0
14       147437   269816    172755     13062  03.29       1565.0          2.0
15       149276   269475    175627     13197  03.30       1803.0          2.0
16       151103   269413    178163     13316  03.31       1787.0          2.0
17       153232   277800    183944     13436  04.01       2086.0          0.0
18       154738   282348    187850     13552  04.02       1455.0          0.0
19       156143   281681    190569     13663  04.03       1366.0          0.0
20       157378   281264    192850     13753  04.04       1173.0          0.0
21       158793   280083    196207     13840  04.05       1383.0          0.0
22       160116   279649    198627     13951  04.06       1284.0          4.0
23       161692   279290    201985     14048  04.07       1540.0          4.0
24       163042   277812    205491     14134  04.08          NaN          NaN
25       164393   276307    208982     14197  04.09       1318.0          0.0
26       165577   275995    211238     14262  04.10       1164.0          0.0
27       140220   275972    213274     14319  04.11       1251.0          0.0
28       168362   275055    216382     14378  04.12       1500.0          0.0
29       171382   275434    219950     14440  04.13       2999.0          0.0

In [67]:
method = {'confirm_add' : df['confirm_add'].mean(), 'suspect_add' : 0}
df  = pd.DataFrame.fillna(df, method)
df.to_dict()

    acc_confirm  confirm  acc_heal  acc_dead   date  confirm_add  suspect_add
0        122456   253686    147084     10057  03.15   1860.00000          1.0
1        123773   256755    148389     10336  03.16   1226.00000          8.0
2        126234   259671    149838     10625  03.17   2388.00000          6.0
3        128462   261879    151526     10892  03.18   2157.00000          0.0
4        130199   263660    153047     11141  03.19   1656.00000          3.0
5        132226   265370    154514     11387  03.20   1947.00000          6.0
6        134564   267730    155494     11610  03.21   2281.00000          0.0
7        137231   269360    157432     11855  03.22   2591.00000          3.0
8        139285   270011    159794     12060  03.23   2010.00000          1.0
9        140651   270903    161905     12261  03.24   1301.00000          5.0
10       141986   270494    164215     12453  03.25   1280.00000          1.0
11       143240   270030    166661     12592  03.26   1217.00000          0.0
12       144515   270118    168586     12743  03.27   1219.00000          6.0
13       145808   270382    170177     12911  03.28   1228.00000          6.0
14       147437   269816    172755     13062  03.29   1565.00000          2.0
15       149276   269475    175627     13197  03.30   1803.00000          2.0
16       151103   269413    178163     13316  03.31   1787.00000          2.0
17       153232   277800    183944     13436  04.01   2086.00000          0.0
18       154738   282348    187850     13552  04.02   1455.00000          0.0
19       156143   281681    190569     13663  04.03   1366.00000          0.0
20       157378   281264    192850     13753  04.04   1173.00000          0.0
21       158793   280083    196207     13840  04.05   1383.00000          0.0
22       160116   279649    198627     13951  04.06   1284.00000          4.0
23       161692   279290    201985     14048  04.07   1540.00000          4.0
24       163042   277812    205491     14134  04.08   1656.37931          0.0
25       164393   276307    208982     14197  04.09   1318.00000          0.0
26       165577   275995    211238     14262  04.10   1164.00000          0.0
27       140220   275972    213274     14319  04.11   1251.00000          0.0
28       168362   275055    216382     14378  04.12   1500.00000          0.0
29       171382   275434    219950     14440  04.13   2999.00000          0.0

In [81]:
train_df = df.iloc[0 : 24]
train_df = train_df.copy()
train_df['date'] = [i for i in range(1, 25)]
test_df = df.iloc[24:]
test_df = test_df.copy()
test_df['date'] = [i for i in range(25, 31)]
test_df

    acc_confirm  confirm  acc_heal  acc_dead  date  confirm_add  suspect_add
24       163042   277812    205491     14134    25   1656.37931          0.0
25       164393   276307    208982     14197    26   1318.00000          0.0
26       165577   275995    211238     14262    27   1164.00000          0.0
27       140220   275972    213274     14319    28   1251.00000          0.0
28       168362   275055    216382     14378    29   1500.00000          0.0
29       171382   275434    219950     14440    30   2999.00000          0.0

In [92]:
X_train = train_df['date'].values.reshape(-1,1)
Y_train = train_df['acc_confirm'].values.reshape(-1,1)
X_test = test_df['date'].values.reshape(-1,1)
Y_test = test_df['acc_confirm'].values.reshape(-1,1)
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print("intercept", model.intercept_)
print("coef", model.coef_)
Y_prid = model.predict(X_test)
print('rmse', metrics.mean_squared_error(Y_test, Y_prid))
final_pred = model.predict([[31]])
print("final predict", final_pred)

intercept [122135.94565217]
coef [[1697.58434783]]
rmse 148445026.01427945
final predict [[174761.06043478]]

In [94]:
X_train = train_df['date'].values.reshape(-1,1)
Y_train = train_df['confirm'].values.reshape(-1,1)
X_test = test_df['date'].values.reshape(-1,1)
Y_test = test_df['confirm'].values.reshape(-1,1)
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print("intercept", model.intercept_)
print("coef", model.coef_)
Y_prid = model.predict(X_test)
print('rmse', metrics.mean_squared_error(Y_test, Y_prid))
final_pred = model.predict([[31]])
print("final predict", final_pred)

intercept [257518.70289855]
coef [[1034.73043478]]
rmse 104155115.67663313
final predict [[289595.34637681]]

In [96]:
X_train = train_df['date'].values.reshape(-1,1)
Y_train = train_df['acc_heal'].values.reshape(-1,1)
X_test = test_df['date'].values.reshape(-1,1)
Y_test = test_df['acc_heal'].values.reshape(-1,1)
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print("intercept", model.intercept_)
print("coef", model.coef_)
Y_prid = model.predict(X_test)
print('rmse', metrics.mean_squared_error(Y_test, Y_prid))
final_pred = model.predict([[31]])
print("final predict", final_pred)

intercept [139965.43478261]
coef [[2426.89521739]]
rmse 34705037.6987006
final predict [[215199.18652174]]

In [98]:
X_train = train_df['date'].values.reshape(-1,1)
Y_train = train_df['acc_dead'].values.reshape(-1,1)
X_test = test_df['date'].values.reshape(-1,1)
Y_test = test_df['acc_dead'].values.reshape(-1,1)
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print("intercept", model.intercept_)
print("coef", model.coef_)
Y_prid = model.predict(X_test)
print('rmse', metrics.mean_squared_error(Y_test, Y_prid))
final_pred = model.predict([[31]])
print("final predict", final_pred)

intercept [10327.27536232]
coef [[169.62130435]]
rmse 529458.7083098594
final predict [[15585.5357971]]

In [100]:
X_train = train_df['date'].values.reshape(-1,1)
Y_train = train_df['confirm_add'].values.reshape(-1,1)
X_test = test_df['date'].values.reshape(-1,1)
Y_test = test_df['confirm_add'].values.reshape(-1,1)
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print("intercept", model.intercept_)
print("coef", model.coef_)
Y_prid = model.predict(X_test)
print('rmse', metrics.mean_squared_error(Y_test, Y_prid))
final_pred = model.predict([[31]])
print("final predict", final_pred)

intercept [1997.45289855]
coef [[-27.11956522]]
rmse 583804.005729683
final predict [[1156.74637681]]

In [101]:
X_train = train_df['date'].values.reshape(-1,1)
Y_train = train_df['suspect_add'].values.reshape(-1,1)
X_test = test_df['date'].values.reshape(-1,1)
Y_test = test_df['suspect_add'].values.reshape(-1,1)
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print("intercept", model.intercept_)
print("coef", model.coef_)
Y_prid = model.predict(X_test)
print('rmse', metrics.mean_squared_error(Y_test, Y_prid))
final_pred = model.predict([[31]])
print("final predict", final_pred)

intercept [3.84782609]
coef [[-0.10782609]]
rmse 0.8129086326402021
final predict [[0.50521739]]